routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FirstController@login');

Route::get('/welcome', function(){
    return 'asdasdsd';
});
Route::get('checkDB', function ()
{
    dd(DB::connection()->getDatabaseName());
});
Route::get('thongtin/{tuoi}/{ten}', function($tuoi, $ten) {
   return "hello $ten , $tuoi tuổi";
})->where(['tuoi' => '[0-9]+', 'ten' => '[a-z]+']);
Route::get('test',function(){
	return view('test');
});
Route::resource('task','crud');
Route::get('add', 'FirstController@add');
Route::post('store','FirstController@store');
Route::get('login', 'FirstController@login');
Route::post('check','loginController@check');
Route::get('logout','loginController@logout');
Route::get('category/{loai}','category@index');
Route::get('angular', function(){
    return view('angular');
});
Route::post('timkiem','FirstController@search');
Route::get('json','FirstController@angular');
Route::post('post','FirstController@guiapi');

resources/views/angular.blade.php
<!DOCTYPE html>
<html lang="en"  >
<head>
  <title>test angular</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="vendor/angular-material.min.css">
</head>
<body ng-app="myApp" ng-controller="MyController">

  <div class="khoi1 cards" ng-show="hienthi">
    <div class="container">   
       <button class="btn btn-info" ng-click="doigiatri()">Add</button>
    </div>
  </div>
  
  <div class="khoi2 cards" ng-show="!hienthi">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
             <div class="card border-primary">
                    <div class="card-header">Add </div>
                    <div class="card-body text-primary">
                        <div class="form-group">
                             <label for="">Gia</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                          <label for="">Loai nha mang</label>
                            <select class="form-control">
                                <option>Mobi</option>
                                <option>Vina</option>
                                <option>Viettel</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary">Add</button>
                            <button class="btn btn-danger" ng-click="doigiatri()" >close</button>
                        </div>
                    </div>
                </div>
        </div>
      </div>
    </div>
    
  </div>
   <div class="container">
       <div class="row">
         <div class="col-xl-4">
             <h1>Live search</h1>
             <input type="text" ng-model="searchText" class="form-control">
           </div>
       </div>
   </div>



    <div class="container">
        <div class="row">
           
            <md-autocomplete
          ng-disabled="ctrl.isDisabled"
          md-no-cache="ctrl.noCache"
          md-selected-item="ctrl.selectedItem"
          md-search-text-change="ctrl.searchTextChange(ctrl.searchText)"
          md-search-text="ctrl.searchText"
          md-selected-item-change="ctrl.selectedItemChange(mot)"
          md-items="mot in nhieunguoi"
          md-item-text="mot.gia"
          md-min-length="0"
          placeholder="Nhap vao tu khoa tim kiem">
        <md-item-template>
          <span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">@{{mot.gia}}</span>
        </md-item-template>
        <md-not-found>
         
          <a ng-click="ctrl.newState(ctrl.searchText)">Create a new one!</a>
        </md-not-found>
      </md-autocomplete>
        </div>
    </div>
  <div class="container">
    <div class="row">
      <table class="table table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                    <thead>
                      <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="
                        Name
                        : activate to sort column descending" style="width: 171px;">
                       SO
                      </th>
                      <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="
                      Position
                      : activate to sort column ascending" style="width: 207px;">
                      Gia
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="
                    Office
                    : activate to sort column ascending" style="width: 174px;">
                    Loai nha mang
                  </th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="
                  Age
                  : activate to sort column ascending" style="width: 140px;">
                  Image
                </th>
                <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="
                Start Date
                : activate to sort column ascending" style="width: 240px;">
                Action
              </th>
            </tr>
          </thead>
      <tbody ng-repeat="mot in nhieunguoi|filter:searchText""  ng-init="mot.hienthi=false">
        <tr ng-show="!mot.hienthi">
          <td>@{{mot.so}}</td>
          <td>@{{mot.gia}}</td>
          <td>@{{mot.loai}}</td>
          <td><img src="@{{mot.anh}}" width="100px" height="50px"></td>
          <td><button class="btn btn-warning" ng-click="hienra(mot)">edit</button></td>
        </tr>
        <!-- xem du lieu -->
        <tr ng-show="mot.hienthi">
          <td><input type="text" class="form-control" ng-model="mot.so" ></td>
          <td><input type="text" class="form-control" ng-model="mot.gia" name="gia"></td>
          <td><select ng-model="mot.loai" id="" class="form-control">
              <option value="Mobi">Mobi</option>
              <option value="Vina">Vina</option>
              <option value="Viettel">Viettel</option>
          </select></td>
          <td><input type="file" class="form-control" ng-model="mot.anh"></td>
          <td><button class="btn btn-primary" ng-click="luudulieu(mot)">save</button></td>
          <td><button class="btn btn-danger " ng-click="hienra(mot)">close</button></td>
        </tr>
      </tbody>

    </table>
  </div>
</div>


<script type="text/javascript" src="vendor/bootstrap.js"></script>  
<script type="text/javascript" src="vendor/angular-1.5.min.js"></script>  
<script type="text/javascript" src="vendor/angular-animate.min.js"></script>
<script type="text/javascript" src="vendor/angular-aria.min.js"></script>
<script type="text/javascript" src="vendor/angular-messages.min.js"></script>
<script type="text/javascript" src="vendor/angular-material.min.js"></script>  
<script type="text/javascript" src="vendor/1.js"></script>

</body>
</html>

resources/views/bai1.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>php</title>
</head>
<body>
	<h2>PHP LARA</h2>
	 <table class="table table-striped">
    <thead>
     <tr>
      <th>So </th>
      <th>Gia</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
   
      
   
   <td>{{$data}}</td>
   <td></td>

  
   
  <td> <a href="">Xoa</a></td>
  <td>
     
     <form action="" method="post">
   
      <a href="" class="btn btn-warning">edit</a>
       <button type="submit" class="btn btn-success">xoa2</button>
     </form>
  </td>

</tbody>
 
</table>
</body>
</html>

resources/views/category.blade.php
@extends('layout')
@section('content')
<div class="container">
	<div class="text-xs-center">
		<h3 class="display-4">LOAI SAN PHAM</h3>
		<hr>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-sm-9 push-sm-1">
			<table class="table table-striped">
				<thead>
					<tr>
						
						<th scope="col">Mã :</th>
						<th scope="col">Gia :</th>
						<th>Edit</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($get_loai as $p)
					<tr>
						<td>{{$p->so}}</td>
						<td>{{$p->gia}}</td>

					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>

@endsection

resources/views/create.blade.php
@extends('layout')

@section('content')

<form action="{{route('task.store')}}" method="POST" enctype="multipart/form-data">
     {{ csrf_field()}}
  
     <div class="row">
        <div >
            <div class="form-group">
                <strong>so:</strong>
                <input type="hidden" name="so" class="form-control" placeholder="so">
            </div>
        </div>
        <div >
            <div class="form-group">
                <strong>gia:</strong>
                <input type="text" class="form-control"  name="gia" placeholder="gia" ></div>
                @if($errors->has('gia'))
                 <p style="color:red">{{$errors->first('gia')}}</p>
                @endif
        </div>
        <div >
            <div class="form-group">
                <strong>Loai:</strong>
                <select class="form-control" name="loai">
                    <option value="Mobi">Mobi</option>
                    <option value="Vina">Vina</option>
                    <option value="Viettel">Viettel</option>
                </select>
        </div>
         <div>
              		<label for="">Upload anh <i class="fa fa-photo"></i> </label>
              		<input name="anh" class="form-control" type="file" required="true">
         </div>
        </div>
       <br>
        <div >
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/edit.blade.php
@extends('layout')
@section('content')
<div class="container">
		<div class="row">
			@foreach($data as $p)
			
				<h2>EDIT</h2>
				<form action="{{route('task.update',$p->so)}}" method="post" enctype="multipart/form-data">		
			{{csrf_field()}}
			{{ method_field('PUT') }}	
				<div class="col-sm-5">
					<div class="form-group">
						<label for="">So: </label>
						<input type="text" class="form-control" name="so" value="{{$p->so}}">
					
					</div>
					<div class="form-group">
						<label for="">Gia</label>
						<input type="text" class="form-control" name="gia" value="{{$p->gia}}" >
						 @if($errors->has('gia'))
                			 <p style="color:red">{{$errors->first('gia')}}</p>
               			 @endif
					</div>
					<div class="form-group">
						<label for="">Loai</label>
						<select class="form-control" name="loai">
                    		<option value="Mobi">Mobi</option>
                   			<option value="Vina">Vina</option>
                 		    <option value="Viettl">Viettel</option>
                 	     </select>
					</div>
					

                	<div class="card">
                		<p for="">Upload anh <i class="fas fa-image"></i> </p>
                		<img src="../../{{$p->anh}}" width="150px" height="100px">      					
              			<input name="anh" class="form-control" type="file" required="true">
                	</div>
                	<br>
					<button type="submit" class="btn btn-success">Update</button>
				</div>
				
			</form>
			
			@endforeach
		</div>
	</div>
	@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<html lang="en" ng-app="my-app" >
<head>
	<title>Laravel</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body >
	
	<div class="container">
		@yield('content')
	</div>

	<script type="text/javascript" src="app/lib/angular.min.js"></script>  
	<script type="text/javascript" src="app/app.js"></script>  
</body>
</html>

resources/views/login.blade.php
@extends('layout')
@section('content')
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-6">Login</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
    <img src="https://via.placeholder.com/350x150" alt="">
  </div>
</div>
<div class="container">
		<div class="row">
			<div class="col-sm-6 ">
				<h4 class="alert alert-success"  style="text-align:center">LOGIN</h4>
			</div>
		</div>
</div>
	<div class="container">
  	<div class="row">
  		<div class="col-lg-6 push-sm-3">
  			<form action="{{url('check')}}" method="post">
              {{ csrf_field()}}
          	
  				<fieldset class="form-group">
              		<label for="">ID:</label>
              		<input name="id" type="text" class="form-control"  required="true">
  				</fieldset>
  				<fieldset class="form-group">
              		<label for="">PASS:</label>
              		<input name="pass" type="password" class="form-control"  required="true">
  				</fieldset>
  				<button type="submit" class="btn btn-danger">LOGIN</button>
  			</form>
  		</div>		
  	</div>
  </div>

@endsection

resources/views/search.blade.php
@extends('layout')
@section('content')
<div class="container">
  <div class="text-xl-center">
    <h3 class="display-4">KET QUA TRA VE</h3>

    <hr>
  </div>
</div>
<div class="container">
  <div class="row">
   @foreach ($kqtimkiem as $p)   
   <div class="col-sm-2"> 
    <div class="card">
      <img class="card-img-top" src="{{$p->anh}}" width="150px" height="100px" >       
      <h5 class="card-title ten">so:{{$p->so}}</h5>
      <p class="card-text tuoi">gia:{{$p->gia}}</p>
      <a href="{{route('task.edit',$p->so)}}" class="btn btn-warning"><i class="far fa-edit"></i></a>
      <a href="" class="btn btn-danger"><i class="fa fa-times"></i></a>

      <p class="card-text"><small class="text-muted">Loai:{{$p->loai}}</small></p>
    </div>  
  </div> 
  @endforeach
</div>  
</div>


@endsection

resources/views/test.blade.php
@extends('layout')
@section('content')

@if(Session::has('name'))
<div class="container">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Tai khoan la: {{ Session::get('name') }}</a>
    <a class="navbar-brand"  href="{{url('logout')}}">Logout <i class="fas fa-sign-out-alt"></i></a>
  </nav>  

</div>


<div class="container">
  <div class="text-xl-center">
    <h3 class="display-4">Danh sach</h3>
    <h4>Tim kiem</h4>
    <form action="{{url('timkiem')}}" method="POST">
     {{ csrf_field()}}
     <input type="text" class="form-control" name="searchText" >
     <br>
     <button type="submit" class="btn btn-primary">Search</button>
   </form>
   <hr>
 </div>
</div>
<div class="container">
  <div class="row">
   @foreach ($db as $p)   
   <div class="col-sm-2"> 
    <div class="card">
      <img class="card-img-top" src="{{$p->anh}}" width="150px" height="100px" >       
      <h5 class="card-title ten">so:{{$p->so}}</h5>
      <p class="card-text tuoi">gia:{{$p->gia}}</p>
      <a href="{{route('task.edit',$p->so)}}" class="btn btn-warning"><i class="far fa-edit"></i></a>
      <a href="" class="btn btn-danger"><i class="fa fa-times"></i></a>

      <p class="card-text"><small class="text-muted">Loai:{{$p->loai}}</small></p>
    </div>  
  </div> 
  @endforeach
</div>  
</div>

{{ $db->links() }}
<h2>PHP LARA</h2>
<a href="{{route('task.create')}}" class="btn btn-primary">Add</a>
@foreach ($loaisp as $q)
<a href="{{url('category',$q->tenloai)}}"    class="btn btn-success">{{$q->tenloai}}</a>
@endforeach

<table class="table table-striped">
  <thead>
   <tr>
    <th>So </th>
    <th>Gia</th>
    <th>Loai</th>
    <th>IMG</th>
    <th>Action</th>
  </tr>
</thead>
<tbody>

 @foreach ($db as $p)
 <tr >
   <td >{{$p->so}}</td>
   <td>{{$p->gia}}</td>
   <td>{{$p->loai}}</td>
   <td><img src="{{$p->anh}}" width="150px" height="100px"></td>
   <td>
    <form action="{{route('task.destroy',$p->so)}}" method="post">
      @csrf
      @method('DELETE')
      <a href="{{route('task.edit',$p->so)}}" class="btn btn-warning"><i class="far fa-edit"></i></a>
      <button type="submit" class="btn btn-success"><i class="fa fa-times"></i></button>
    </form>
  </td>
</tr>

</tbody>
@endforeach
</table>
@endif




@endsection